### ISSUE TITLE
3D_alltube

### ISSUE THREAD

**Issue by MichalTJE** [nixgates/Incursion#30]
Hello, is there a chance to polish the 3D designation from the alltube so that Incursion shows it? it's about Polish sources

**Comment by bugatsinho** [comment]
i managed to adjust the scraper to scrape the normal and the 3D version of the movie and also some extras for the series.Also i know it isnt fancy but i faced an error with TWD show because the title was like Walking Dead, The so error with the comparison! here is my py @nixgates 

[alltube.py.zip](https://github.com/nixgates/Incursion/files/1948903/alltube.py.zip)

**Comment by MichalTJE** [comment]
thank you

**Comment by nixgates** [comment]
Bugatsinho's fix will be implemented in the next update.
