### ISSUE TITLE
How often changes will be approved

### ISSUE THREAD

**Issue by tomasiek** [nixgates/Incursion#41]
How often do you plan to approve changes? Recently, we have been waiting a bit and changes have been approved and new ones have already arrived in the sources (mainly in PL)

**Comment by nixgates** [comment]
To be honest, I couldn't give you an accurate timeframe. I try to get to them when I see them, currently I don't keep track of when a new PR is made but I will write a script to notify me when one is made. 

I'll investigate the current PR's again tomorrow and incorporate relevant updates. I'm sorry, its a shitty excuse but I am the only developer behind Incursion at the moment and I am looking at creating a complete re-write with a bunch of new features so updates beyond scrapers are on the lowest priority at this moment and even scraper updates will need to wait until I see and evaluate them.

I'm closing this issue, I hope youre ok with the info I gave you? Otherwise feel free to get in contact with me.

**Comment by tomasiek** [comment]
Someone has sent corrections to Polish sources today. From what I saw, they take into account the latest changes on Polish pages. Probably change cloudflare will force something.
