### ISSUE TITLE
Latest Watchnixtoons issue

### ISSUE THREAD

**Issue by bjgood** [nixgates/Incursion#53]
Hey nixgates,
I don't know if it's just me, but the new Watchnixtoons 1.0.2 is only playing cartoons in 720p. Anything SD will not play, which includes a lot of our favorites. Watchnixtoons 1.0.1 played both SD and 720. Let me list a few that don't play that you can check....
Back at the Barnyard, Men in Black, The Mighty B!, Monsters vs. Aliens, The Penguins of Madagascar, Planet Sheen, Puss in Boots, Shaun the Sheep, The Smurfs, The Wild Thornberrys, T.U.F.F. Puppy, Invader Zim, and others.

The point is, any cartoon having only SD episodes will not play. If it has 720p links then it does play.

It could be that the site has switched to 720p only. Just a thought.

BTW, thanks for the update, Dev. I appreciate the effort that you put into all your projects. Incursion user here. :).

Later...
Bob

**Comment by dokoab** [comment]
From what I tested (watched Back at the Barnyard, thanks for making that list for error checking btw), this update lets you watch it. It's due a revision before the addon is updated automatically.

If you're in a hurry, you can download this file...  
https://github.com/dokoab/Incursion/raw/master/plugin.video.watchnixtoons/default.py

...and copy it over the same-name one installed in Kodi. It's in the **plugin.video.watchnixtoons** folder inside the Kodi addons folder:
**Android:** /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/ (the .kodi folder is hidden, use ES File Explorer with the "Show hidden files" option)
**Windows:** AppData/Roaming/Kodi/addons/
**Linux:** /home/USER/.kodi/addons/

Again, you only need to do this if you want the update *immediately*. Otherwise just wait and the addon will be updated automatically some time from now (no idea when).

**Comment by dokoab** [comment]
Oh and for Back at the Barnyard at least, there was only one quality available. So other shows might be the same.

**Comment by bjgood** [comment]
Thanks, dokoab. I'll check it out right now. I'll post back with my results.

Thanks, again.

Bob

**Comment by bjgood** [comment]
Success! After changing out the default.py file everything seems to be working again. Thank you so much (from my kids and me) for posting the solution in this thread. 

Thanks, dokoab. :).

Best regards,
Bob

**Comment by chewvodka** [comment]
I'm at work, so I won't be able to test and confirm this till later tonight.  But sounds promising.  Thanks!

**Comment by bjgood** [comment]
I'd like to add that with Watchnixtoons 1.0.1 Garfield and Friends would play episodes in SD. Now with Watchnixtoons 1.0.2 plus dokoab's revised default.py (thanks once again...:)) Garfield and Friends only plays is 720p. No big deal. I can live with that. Just thought I'd point it out. I'm glad to have Watchnixtoons up and working once again.

Have a good day everybody. :).

Later...
Bob

**Comment by chewvodka** [comment]
All working great now thanks!  Now all we need is Trakt support.  ;)

**Comment by major48** [comment]
It was up for a while for me but now it's not working again.

**Comment by dokoab** [comment]
There's another pull-request ("update") that might bring more source qualities back: https://github.com/nixgates/Incursion/pull/56

The link to that updated default.py can be found by going to the "Files changed" tab, then clicking the "View" button on the default.py changes. It leads to a page where you can download the file by right-clicking the "Raw" button:
https://github.com/alexnander/Incursion/blob/f41fd510ddea7f3c8f012f9044d5121299d7f916/plugin.video.watchnixtoons/default.py

The reason I'm saying all this is because anytime you see a PR and want to download its default.py file, you can do it this way.

**Comment by lorkadiscovery** [comment]
It can be done as follows if people prefer it.

![untitled](https://user-images.githubusercontent.com/34162321/38778999-fb6b95d8-40b9-11e8-8913-2c403b930a83.png)

**Comment by bjgood** [comment]
Hey dokoab,
"Looking at the code, the addon always tries to play 1080p or 720p qualities first, and if there are none then it plays the SD source.
When my network speed is slow i prefer using SD sources... are you after some like this, being able to choose?"

I'm like you, dokoab. I prefer SD because my internet can be flaky at times.

And, yes, I'd like the option to choose which quality to use.

Thanks again for the fix yesterday. :). It made for a very pleasant evening for the kids.

Later...
Bob

**Comment by lorkadiscovery** [comment]
@bjgood As you can see in my screenshot above, the option to select a quality (if only one quality is available that will be played with no dialog) is easy to add. Even adding to the settings to show dialog or pick autoplay is easy to do. I can PR whatever anyone wants.

**Comment by bjgood** [comment]
Give it a shot, lorkadiscovery. I love experimenting. :).

BTW, I run LibreELEC on a RPi3.

Later...
Bob

**Comment by lorkadiscovery** [comment]
https://github.com/nixgates/Incursion/pull/57

Give the defauly.py a try and see how you like it ^^^

**Comment by bjgood** [comment]
Hey lorkadiscovery,
I looked at your code and I was wondering if you could change it to automatically play SD (if available) instead of bringing up a dialog box? If SD is not available then play 720p.

**Comment by lorkadiscovery** [comment]
@bjgood What we could do is add a setting option:

Playback Option: [Auto Play Highest Resolution|Auto Play Lowest Resolution|Select Via Dialog]

Thoughts?

Pick in settings (Dialog by default) and then the function can do whatever the user selects.

**Comment by bjgood** [comment]
Hey lorkadiscovery,
Wow! As of right now...it's perfect! It works great! It plays Garfield and Friends, which normally only plays in 720p, in SD! Terrific!

You've done a great job coding. Amazing...at least as of right now. I'll continue to check it out, but as of right now it's perfect.

Thanks, buddy. :). Wow!

Best regards,
Bob

**Comment by dokoab** [comment]
@lorkadiscovery how kind!
You and @alexnander did some great PRs.

**Comment by lorkadiscovery** [comment]
No problem guys.

**Comment by major48** [comment]
Still not working for me. Trying to watch Black Butler (Dubbed)

**Comment by daniel-ntl** [comment]
please update to 1.03 thx

**Comment by major48** [comment]
I just changed the default.py file. I will try to update to 1.03 later when I get home

**Comment by major48** [comment]
When i try to get update im still only getting 1.02

**Comment by daniel-ntl** [comment]
yup now i know why it didnt work in jarvis 16.1 its because the phyton.....so now i'm using cemc, and the addons works but i have some issues if you already play 01 episode on the same page, the next one the 02 episode cannot play, how come?

**Comment by dokoab** [comment]
@major48 if you're using @lorkadiscovery's pull-request (57) then you also need to install he resources/settings.xml file, as that default.py needs that.
The addon hasn't been updated to 1.03 yet, so trying to update it through Kodi won't make a difference. Installing files manually like we're doing is an advanced use, if you're having trouble it's best to wait for it to be updated by @nixgates officially. When nixgates does it, they advance the addon version in the addon.xml file, and we haven't touched this file for now (that's why it's still 1.02). 

@daniel-ntl if you're having some specific error then maybe it's best to [open a new issue](https://github.com/nixgates/Incursion/issues/new) to keep the bug tracker organised and to not have it lost when this thread is closed.

**Comment by major48** [comment]
@dokoab that worked. I had forgot the settings.xml. Thanks

**Comment by nixgates** [comment]
Lorka's PR has been incorporated into the main release.

Closing Issue :)
